export const ADD_CHECKING_ACCOUNTS = 'ADD_CHECKING_ACCOUNTS';
export const CHECKING_ACCOUNTS_LOADING = 'CHECKING_ACCOUNTS_LOADING';
export const CHECKING_ACCOUNTS_FAILED = 'CHECKING_ACCOUNTS_FAILED';

export const ADD_SAVINGS_ACCOUNT = 'ADD_SAVINGS_ACCOUNT';
export const SAVINGS_ACCOUNT_LOADING = 'SAVINGS_ACCOUNT_LOADING';
export const SAVINGS_ACCOUNT_FAILED = 'SAVINGS_ACCOUNT_FAILED';

export const ADD_CDACCOUNT = 'ADD_CDACCOUNT';
export const CDACCOUNT_LOADING = 'CDACCOUNT_LOADING';
export const CDACCOUNT_FAILED = 'CDACCOUNT_FAILED';

export const ADD_USER = "ADD_USER";
export const USER_LOADING = "USER_LOADING";
export const USER_FAILED = "USER_FAILED";
